num_actions: 12
dof_config:
  isaac_order:
  - l_hip_z_joint
  - l_hip_x_joint
  - l_hip_y_joint
  - l_knee_y_joint
  - l_ankle_y_joint
  - l_ankle_x_joint
  - r_hip_z_joint
  - r_hip_x_joint
  - r_hip_y_joint
  - r_knee_y_joint
  - r_ankle_y_joint
  - r_ankle_x_joint
  l_hip_z_joint:
    kp: 100.0
    kd: 3.0
    action_scale: 0.5
    torque_limits: 17.100000381469727
    default_pos: 0.0
  l_hip_x_joint:
    kp: 100.0
    kd: 3.0
    action_scale: 0.5
    torque_limits: 38.0
    default_pos: 0.0
  l_hip_y_joint:
    kp: 100.0
    kd: 3.0
    action_scale: 0.5
    torque_limits: 47.5
    default_pos: -0.30000001192092896
  l_knee_y_joint:
    kp: 100.0
    kd: 3.0
    action_scale: 0.5
    torque_limits: 104.5
    default_pos: 0.6000000238418579
  l_ankle_y_joint:
    kp: 20.0
    kd: 0.8999999761581421
    action_scale: 0.5
    torque_limits: 47.5
    default_pos: -0.30000001192092896
  l_ankle_x_joint:
    kp: 20.0
    kd: 0.8999999761581421
    action_scale: 0.5
    torque_limits: 19.0
    default_pos: 0.0
  r_hip_z_joint:
    kp: 100.0
    kd: 3.0
    action_scale: 0.5
    torque_limits: 17.100000381469727
    default_pos: 0.0
  r_hip_x_joint:
    kp: 100.0
    kd: 3.0
    action_scale: 0.5
    torque_limits: 38.0
    default_pos: 0.0
  r_hip_y_joint:
    kp: 100.0
    kd: 3.0
    action_scale: 0.5
    torque_limits: 47.5
    default_pos: -0.30000001192092896
  r_knee_y_joint:
    kp: 100.0
    kd: 3.0
    action_scale: 0.5
    torque_limits: 104.5
    default_pos: 0.6000000238418579
  r_ankle_y_joint:
    kp: 20.0
    kd: 0.8999999761581421
    action_scale: 0.5
    torque_limits: 47.5
    default_pos: -0.30000001192092896
  r_ankle_x_joint:
    kp: 20.0
    kd: 0.8999999761581421
    action_scale: 0.5
    torque_limits: 19.0
    default_pos: 0.0
obs_config:
  sensors:
    base_ang_vel:
      shape:
      - 3
      obs_scale: 1.0
      frames: 1
    base_euler_xyz:
      shape:
      - 3
      obs_scale: 1.0
      frames: 1
    command_lin_vel:
      shape:
      - 2
      obs_scale: 1.0
      frames: 1
    command_ang_vel:
      shape:
      - 1
      obs_scale: 1.0
      frames: 1
    sin_phase:
      shape:
      - 2
      obs_scale: 1.0
      frames: 1
    dof_pos:
      shape:
      - 12
      obs_scale: 1.0
      frames: 1
    dof_vel:
      shape:
      - 12
      obs_scale: 0.05
      frames: 1
    actions:
      shape:
      - 12
      obs_scale: 1.0
      frames: 1
  actor_obs:
    sources:
    - base_ang_vel
    - base_euler_xyz
    - command_lin_vel
    - command_ang_vel
    - sin_phase
    - dof_pos
    - dof_vel
    - actions
    history_len: 10
    flatten: true
pd_rate: 1000.0
infer_rate: 99.9999952502551
step_period: 0.32
stand_rate: 0.55
clip_actions: 100.0
clip_obs: 100.0
